AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.small
    Description: Enter instance size. Default is t2.small.
  AMI:
    Type: String
    Default: ami-0e001c9271cf7f3b9
    Description: The Ubuntu AMI to use.
  Key:
    Type: String
    Description: Enter key name
  VPC:
    Type: String
    
    Description: Default VPC ID.
  Subnet:
    Type: String
    
    Description: Subnet ID.
  SecurityGroupName:
    Type: String
    Default: mysecGP
    Description: Name for security group.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SecurityGroupName
      GroupDescription: "Security Group for jenkins"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '0'
          ToPort: '65535'
          CidrIp:  0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  
  mysecGP:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: InstanceTypeParameter
      KeyName: !Ref Key
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo apt-get update -y
          sudo apt-get install openjdk-17-jdk -y
          curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
          echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
          sudo apt-get update -y
          sudo apt-get install jenkins -y
          sudo systemctl enable jenkins
          sudo systemctl start jenkins
      Tags:
        - Key: Name
          Value: myjenkins_machine
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - mysecGP
        - PublicIp
    Description: Server's PublicIp Address